/* data.js — what the trainer asks, authored against the ORIGINAL node names in the
 * Z-Anatomy exports (GLTFLoader keeps them in userData.name; side suffix .l/.r stripped,
 * lower-cased before matching).
 *
 * her:1   keyed somewhere in the HS2 Module 2 quiz bank (471 questions, read by hand
 *         20 Sep 2026). That is the "Her list" scope and the default.
 * clue    a one-line prompt. hers:1 = paraphrased from one of her own questions.
 * deep:1  cannot be tapped from outside — asked in "Name it" only, with the body x-rayed.
 * on/p    a LANDMARK: a point on one bone, in that mesh's own bounding-box coordinates
 *         (0..1 on each axis), so it lands on both the left and the right copy.
 * az/el   camera azimuth/elevation in degrees (0 = from the front, 180 = from behind).
 */

/* hip bone, mesh-local 0..1 coordinates (x lateral→medial, y up, z back→front on the right-side copy;
 * the left copy is the same mesh mirrored, so the same numbers land on it). */
const HIP_SIZE = [0.132, 0.215, 0.143];
const HIP_C = { ilium:[0.36,0.78,0.483], pubis:[0.817,0.208,0.806], ischium:[0.606,0.162,0.359] };
const ACETAB = [0.282,0.439,0.639];
const CREST = [0.86,0.91,0.97,0.99,1,0.99,0.97,0.92,0.86,0.8];       // top-edge height in ten back→front slices
const md = (a, b) => Math.hypot((a[0]-b[0])*HIP_SIZE[0], (a[1]-b[1])*HIP_SIZE[1], (a[2]-b[2])*HIP_SIZE[2]);
export function hipPart(n) { if (md(n, ACETAB) < 0.03) return 'acetabulum'; let best = null; for (const k in HIP_C) { const d = md(n, HIP_C[k]); if (!best || d < best.d) best = { k, d }; } return best.k; }
const onCrest = n => n[1] > 0.6 && n[1] >= CREST[Math.min(9, Math.max(0, Math.floor(n[2] * 10)))] - 0.075;
/* A tap that is honestly neither right nor wrong. */
export const NEUTRAL = { 'hip bone': n => hipPart(n) === 'acetabulum' ? { title:'Acetabulum', sub:'the hip socket — ilium, ischium and pubis all meet in it, so it belongs to none of them alone' } : null };

const RIB = n => new RegExp('^(' + n + ') rib$');

export const BONES = [
  // ── the two divisions (her true/false pair: "the clavicle is axial" — false; "skull and mandible are appendicular" — false) ──
  { id:'axial', name:'Axial skeleton', her:1, region:'whole', az:20,
    m:[/^(frontal|parietal|occipital|temporal|sphenoid|ethmoid|zygomatic|nasal|lacrimal|palatine|inferior nasal concha|hyoid) bone$/, 'maxilla', 'mandible', 'vomer',
       /^(upper|lower) (canine|lateral incisor|medial incisor|first|second)/, / rib$/, /^(body of sternum|manubrium of sternum|xiphoid process)$/,
       /^(atlas|axis) \(c[12]\)$/, /^vertebra [ctl]\d+$/, 'sacrum', 'coccyx'],
    clue:{ t:'The skull and mandible belong to this division of the skeleton — the clavicle does not.', hers:1 },
    fact:'Skull, hyoid, vertebral column (with sacrum and coccyx), ribs and sternum — the central axis. 80 bones.' },
  { id:'appendicular', name:'Appendicular skeleton', her:1, region:'whole', az:20,
    m:['clavicle', 'scapula', 'humerus', 'radius', 'ulna', /^(capitate|hamate|lunate|pisiform|scaphoid|trapezium|trapezoid|triquetrum) bone$/, /metacarpal bone$/, /phalanx of /,
       'hip bone', 'femur', 'patella', 'tibia', 'fibula', /^(calcaneus|talus|cuboid bone|navicular bone|(intermediate|lateral|medial) cuneiform bone)$/, /metatarsal bone$/],
    clue:{ t:'The clavicle belongs to this division of the skeleton, even though it sits on the trunk.', hers:1 },
    fact:'The limbs plus the girdles that hang them on the axis: clavicle + scapula, and the hip bones. 126 bones.' },

  // ── skull & neck ──
  { id:'cranium', name:'Cranium', common:'Skull (braincase)', her:1, region:'head', az:25,
    m:[/^(frontal|parietal|occipital|temporal|sphenoid|ethmoid) bone$/],
    fact:'The braincase: frontal, parietal, temporal, occipital, sphenoid, ethmoid. Her quiz: the skull is made of flat bones; it is axial skeleton.' },
  { id:'mandible', name:'Mandible', common:'Lower jaw', her:1, region:'head', az:25,
    m:['mandible', /^lower (canine|lateral incisor|medial incisor|first|second)/],
    fact:'Lower jaw — the only skull bone that moves freely.' },
  { id:'maxilla', name:'Maxilla', common:'Upper jaw', her:1, region:'head', az:20,
    m:['maxilla', /^upper (canine|lateral incisor|medial incisor|first|second)/],
    fact:'Upper jaw. A dental abscess in the upper teeth sits in this bone.' },
  { id:'hyoid', name:'Hyoid', her:1, region:'head', az:35, el:-5,
    m:['hyoid bone'],
    clue:{ t:'The only bone that does not articulate with any other bone.', hers:1 },
    fact:'U-shaped bone in the neck, hanging below the mandible. It articulates with no other bone.' },
  { id:'frontal', name:'Frontal bone', common:'Forehead', region:'head', az:15, m:['frontal bone'], fact:'Forehead. One of the cranial bones.' },
  { id:'parietal', name:'Parietal bone', region:'head', az:60, el:25, m:['parietal bone'], fact:'Paired — roof and sides of the cranium.' },
  { id:'temporal', name:'Temporal bone', region:'head', az:85, m:['temporal bone'], fact:'Side of the skull around the ear. The ossicles (malleus, incus, stapes — the smallest bone) sit inside it.' },
  { id:'occipital', name:'Occipital bone', region:'head', az:180, el:-5, m:['occipital bone'], fact:'Back and base of the skull; the spinal cord passes through its foramen magnum.' },
  { id:'zygomatic', name:'Zygomatic bone', common:'Cheek bone', region:'head', az:40, m:['zygomatic bone'], fact:'Cheek bone — a facial bone, not part of the cranium.' },
  { id:'nasal', name:'Nasal bone', region:'head', az:20, m:['nasal bone'], fact:'The bridge of the nose.' },

  // ── thorax & spine ──
  { id:'clavicle', name:'Clavicle', common:'Collar bone', her:1, region:'upper', az:0,
    m:['clavicle'],
    clue:{ t:'The first bone in the body to ossify — and it belongs to the appendicular skeleton.', hers:1 },
    fact:'Collar bone. Appendicular skeleton (pectoral girdle), first bone to ossify.' },
  { id:'scapula', name:'Scapula', common:'Shoulder blade', her:1, region:'upper', az:180,
    m:['scapula'], fact:'Shoulder blade — flat, triangular, on the back of the rib cage.' },
  { id:'sternum', name:'Sternum', common:'Breastbone', her:1, region:'upper', az:0,
    m:[/^(body of sternum|manubrium of sternum|xiphoid process)$/],
    fact:'Breastbone: manubrium, body, xiphoid process. Her skeleton figure labels the body.' },
  { id:'ribs', name:'Ribs', her:1, region:'upper', az:20,
    m:[RIB('first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|eleventh|twelfth')],
    fact:'12 pairs. All of them articulate posteriorly with the vertebral column.' },
  { id:'true-ribs', name:'True ribs', her:1, region:'upper', az:20,
    m:[RIB('first|second|third|fourth|fifth|sixth|seventh')],
    clue:{ t:'Ribs 1 to 7 — each reaches the sternum by its own cartilage.', hers:1 },
    fact:'Ribs 1–7: each has its own costal cartilage to the sternum.' },
  { id:'false-ribs', name:'False ribs', her:1, region:'upper', az:20,
    m:[RIB('eighth|ninth|tenth')],
    clue:{ t:'Ribs 8 to 10 — they reach the sternum only through a shared cartilage.', hers:1 },
    fact:'Ribs 8–10: attach to the sternum via a shared cartilage.' },
  { id:'floating-ribs', name:'Floating ribs', her:1, region:'upper', az:160,
    m:[RIB('eleventh|twelfth')],
    clue:{ t:'Ribs 11 and 12 — not attached to the sternum at all.', hers:1 },
    fact:'Ribs 11–12: no attachment to the sternum.' },
  { id:'column', name:'Vertebral column', alt:'Vertebrae', common:'Spine / backbone', her:1, region:'upper', az:180,
    m:[/^(atlas|axis) \(c[12]\)$/, /^vertebra [ctl]\d+$/, 'sacrum', 'coccyx'],
    fact:'7 cervical + 12 thoracic + 5 lumbar vertebrae, then the sacrum and coccyx. Every rib articulates with it.' },
  { id:'cervical', name:'Cervical vertebrae', her:1, region:'upper', az:160,
    m:[/^(atlas|axis) \(c[12]\)$/, /^vertebra c\d$/],
    clue:{ t:'The vertebrae injured in whiplash.', hers:1 },
    fact:'C1–C7, the neck. C1 is the atlas, C2 the axis (a pivot joint between them).' },
  { id:'thoracic', name:'Thoracic vertebrae', her:1, region:'upper', az:180,
    m:[/^vertebra t\d+$/], fact:'T1–T12 — the ones that carry the ribs.' },
  { id:'lumbar', name:'Lumbar vertebrae', her:1, region:'upper', az:180,
    m:[/^vertebra l\d$/], fact:'L1–L5, the lower back — the biggest vertebral bodies.' },
  { id:'sacrum', name:'Sacrum', her:1, region:'pelvis', az:180,
    m:['sacrum'], fact:'Five fused vertebrae wedged between the two hip bones.' },
  { id:'coccyx', name:'Coccyx', common:'Tailbone', her:1, region:'pelvis', az:180, el:-10,
    m:['coccyx'], fact:'Tailbone — the tip of the vertebral column.' },
  { id:'atlas', name:'Atlas (C1)', region:'head', az:180, el:-5, m:['atlas (c1)'], fact:'C1 — carries the skull. The atlanto-occipital joint is the fulcrum of her first-class lever.' },
  { id:'axis', name:'Axis (C2)', region:'head', az:180, el:-5, m:['axis (c2)'], fact:'C2 — the pivot joint with the atlas turns the head.' },
  { id:'manubrium', name:'Manubrium', region:'upper', az:0, m:['manubrium of sternum'], fact:'Top part of the sternum; the clavicles join here.' },
  { id:'xiphoid', name:'Xiphoid process', region:'upper', az:0, m:['xiphoid process'], fact:'The small tip at the bottom of the sternum.' },

  // ── upper limb ──
  { id:'humerus', name:'Humerus', common:'Upper arm bone', her:1, region:'upper', az:0,
    m:['humerus'],
    clue:{ t:'The "funny bone" is really the ulnar nerve crossing this bone\'s medial epicondyle.', hers:1 },
    fact:'Upper arm. A long bone.' },
  { id:'radius', name:'Radius', her:1, region:'forearm', az:0,
    m:['radius'],
    clue:{ t:'The lateral bone of the forearm — the thumb side.' },
    fact:'Lateral forearm bone (thumb side).' },
  { id:'ulna', name:'Ulna', her:1, region:'forearm', az:0,
    m:['ulna'],
    clue:{ t:'The medial bone of the forearm.', hers:1 },
    fact:'Medial forearm bone (little-finger side); its olecranon is the point of the elbow.' },
  { id:'carpals', name:'Carpals', common:'Wrist bones', her:1, region:'hand', az:0,
    m:[/^(capitate|hamate|lunate|pisiform|scaphoid|trapezium|trapezoid|triquetrum) bone$/],
    fact:'Eight small wrist bones. Carpals = wrist, tarsals = ankle.' },
  { id:'metacarpals', name:'Metacarpals', common:'Palm bones', her:1, region:'hand', az:0,
    m:[/metacarpal bone$/], fact:'Five bones of the palm, between the carpals and the phalanges.' },
  { id:'phalanges-hand', name:'Phalanges', sub:'fingers', common:'Finger bones', her:1, region:'hand', az:0,
    m:[/phalanx of .* of hand$/], accept:['phalanges-foot'],
    fact:'Finger AND toe bones share the name. 14 in each hand, 14 in each foot.' },

  // ── pelvis & lower limb ──
  { id:'hip-bone', name:'Hip bone', alt:'Os coxae', her:1, region:'pelvis', az:20,
    m:['hip bone'],
    clue:{ t:'Ilium + ischium + pubis, fused into one bone.', hers:1 },
    fact:'Os coxae = ilium + ischium + pubis fused. Two of them + sacrum + coccyx = the pelvis.' },
  { id:'pelvis', name:'Pelvis', her:1, region:'pelvis', az:15,
    m:['hip bone', 'sacrum', 'coccyx'],
    clue:{ t:'The two hip bones together with the sacrum and the coccyx.', hers:1 },
    fact:'Two hip bones + sacrum + coccyx. Female: lighter, thinner bones, wider.' },
  { id:'femur', name:'Femur', common:'Thigh bone', her:1, region:'lower', az:0,
    m:['femur'],
    clue:{ t:'The longest, strongest bone — two trochanters for muscles, two condyles for the knee.', hers:1 },
    fact:'Thigh bone: longest and strongest, bears the greatest stress.' },
  { id:'patella', name:'Patella', common:'Knee cap', her:1, region:'lower', az:0,
    m:['patella'], fact:'Knee cap — a sesamoid bone inside the quadriceps tendon.' },
  { id:'tibia', name:'Tibia', common:'Shin bone', her:1, region:'leg', az:0,
    m:['tibia'],
    clue:{ t:'The medial, weight-bearing bone of the lower leg.' },
    fact:'Shin bone — medial, and the one that bears the weight.' },
  { id:'fibula', name:'Fibula', common:'Calf bone', her:1, region:'leg', az:0,
    m:['fibula'],
    clue:{ t:'The lateral bone below the knee and above the ankle — it bears no weight.', hers:1 },
    fact:'Lateral lower-leg bone. Bears no weight.' },
  { id:'tarsals', name:'Tarsals', common:'Ankle bones', her:1, region:'foot', az:35, el:25,
    m:[/^(calcaneus|talus|cuboid bone|navicular bone|(intermediate|lateral|medial) cuneiform bone)$/],
    fact:'Seven ankle bones, including the calcaneus (heel) and talus. Tarsals = ankle, carpals = wrist.' },
  { id:'metatarsals', name:'Metatarsals', her:1, region:'foot', az:35, el:25,
    m:[/metatarsal bone$/], fact:'Five bones of the foot between the tarsals and the toes.' },
  { id:'phalanges-foot', name:'Phalanges', sub:'toes', common:'Toe bones', her:1, region:'foot', az:35, el:25,
    m:[/phalanx of .* of foot$/], accept:['phalanges-hand'],
    fact:'Toe bones — same name as the finger bones.' },
  { id:'calcaneus', name:'Calcaneus', common:'Heel bone', region:'foot', az:150, el:10, m:['calcaneus'], fact:'Heel bone — the largest tarsal. The Achilles (calcaneal) tendon inserts here.' },
  { id:'talus', name:'Talus', region:'foot', az:35, el:25, m:['talus'], fact:'The tarsal that sits under the tibia and forms the ankle joint.' },

  // ── landmarks: a sphere (p + r, metres) or a zone (function of the mesh-local 0..1 point) ──
  //    measured off the mesh itself 20 Sep 2026: sphere-fit head (r 24.7 mm), centroid of each
  //    trochanter / condyle, Voronoi of the three hip-part centroids, crest = the top-edge profile.
  { id:'ilium', name:'Ilium', her:1, on:'hip bone', p:HIP_C.ilium, zone:n => hipPart(n) === 'ilium', region:'pelvis', az:35,
    fact:'The big upper wing of the hip bone. Its top edge is the iliac crest.' },
  { id:'ischium', name:'Ischium', her:1, on:'hip bone', p:[0.66,0.06,0.36], zone:n => hipPart(n) === 'ischium', region:'pelvis', az:160, el:-15,
    fact:'The lower, back part of the hip bone — what you sit on.' },
  { id:'pubis', name:'Pubis', her:1, on:'hip bone', p:[0.9,0.24,0.9], zone:n => hipPart(n) === 'pubis', region:'pelvis', az:0,
    fact:'The lower, front part of the hip bone; the two meet at the pubic symphysis.' },
  { id:'iliac-crest', name:'Iliac crest', her:1, prio:2, on:'hip bone', p:[0.295,1,0.414], zone:onCrest, region:'pelvis', az:35, el:20,
    fact:'The curved top edge of the ilium — what your hands rest on at your hips.' },
  { id:'femur-head', name:'Head of femur', her:1, on:'femur', p:[0.544,0.945,0.696], r:0.027, region:'femur', az:0,
    fact:'The ball that fits the hip socket (acetabulum) — a ball-and-socket joint.' },
  // neck = the waist of the head→trochanter axis: slices perpendicular to it are roundest and narrowest (r 16.8 mm) 20–24 mm from the head centre
  { id:'femur-neck', name:'Neck of femur', her:1, on:'femur', p:[0.405,0.909,0.667], r:0.021, region:'femur', az:0,
    fact:'The narrowed part below the head — where a "broken hip" usually breaks.' },
  { id:'greater-trochanter', name:'Greater trochanter', her:1, on:'femur', p:[0.135,0.911,0.58], r:0.03, region:'femur', az:0,
    fact:'The big lateral bump at the top of the femur. A trochanter is a very large process for muscle attachment — only the femur has them.' },
  { id:'lesser-trochanter', name:'Lesser trochanter', her:1, on:'femur', p:[0.474,0.803,0.398], r:0.018, region:'femur', az:180,
    fact:'The smaller bump, medial and at the back, just below the neck.' },
  { id:'medial-condyle', name:'Medial condyle', sub:'femur', her:1, on:'femur', p:[0.83,0.044,0.297], r:0.03, region:'femur', az:180, el:-10,
    fact:'A condyle is a rounded bump that fits into a joint. The femur has two for the knee; this is the inner one.' },
  { id:'lateral-condyle', name:'Lateral condyle', sub:'femur', her:1, on:'femur', p:[0.406,0.045,0.333], r:0.03, region:'femur', az:180, el:-10,
    fact:'The outer of the two rounded knuckles at the knee end of the femur.' },
];

export const MUSCLES = [
  // ── her labelled figure, front ──
  { id:'deltoid', name:'Deltoid', her:1, region:'upper', az:40,
    m:[/part of deltoid muscle$/],
    clue:{ t:'The triangular shoulder muscle that abducts the arm — named for its shape.', hers:1 },
    fact:'Triangular shoulder muscle, abducts the arm. Named for its shape. An IM injection site.' },
  { id:'pec-major', name:'Pectoralis major', her:1, region:'upper', az:0,
    m:[/pectoralis major muscle\)?$/], fact:'The big chest muscle. (Pectoralis MINOR, underneath, is named for relative size.)' },
  { id:'biceps-brachii', name:'Biceps brachii', her:1, region:'upper', az:15,
    m:[/head of biceps brachii$/],
    clue:{ t:'Flexes the arm at the elbow — named for its two origins.', hers:1 },
    fact:'Flexes the elbow (a third-class lever). Two origins. Its antagonist is the triceps.' },
  { id:'rectus-abdominis', name:'Rectus abdominis', her:1, region:'trunk', az:0,
    m:['rectus abdominis muscle'],
    clue:{ t:'Tone this one for the "six-pack".', hers:1 },
    fact:'"Rectus" = fibres run parallel (straight). The six-pack muscle.' },
  { id:'external-oblique', name:'External oblique', alt:'Obliques', her:1, region:'trunk', az:50,
    m:['external abdominal oblique muscle'], fact:'The side of the abdomen; fibres run diagonally. Her figure labels it "Obliques".' },
  { id:'finger-flexors', name:'Finger flexors', sub:'front of forearm', her:1, region:'forearm', az:0,
    m:[/flexor digitorum superficialis$/, 'flexor digitorum profundus', 'flexor carpi radialis', /flexor carpi ulnaris$/, 'palmaris longus muscle'],
    fact:'The anterior forearm group. "Flexor digitorum" is named for its action.' },
  { id:'quadriceps', name:'Quadriceps femoris', alt:'Quadriceps (4 muscles)', her:1, region:'lower', az:10,
    m:['rectus femoris muscle', /^vastus (lateralis|medialis|intermedius) muscle$/],
    clue:{ t:'The most powerful muscle in the body — four heads on the front of the thigh.', hers:1 },
    fact:'Rectus femoris + vastus lateralis, medialis and intermedius. They join the quadriceps tendon → patella → patellar ligament → tibia.' },
  { id:'tibialis-anterior', name:'Tibialis anterior', her:1, region:'leg', az:20,
    m:['tibialis anterior muscle'], fact:'The shin muscle, lateral to the tibia. Lifts the foot (dorsiflexion).' },
  { id:'sartorius', name:'Sartorius', her:1, region:'lower', az:10,
    m:['sartorius muscle'],
    clue:{ t:'The longest muscle in the body — from the lateral hip to the medial knee.', hers:1 },
    fact:'Longest muscle: a strap crossing the thigh from the lateral hip to the medial side of the knee.' },
  { id:'sternocleidomastoid', name:'Sternocleidomastoid', her:1, region:'head', az:40,
    m:['sternocleidomastoid muscle'],
    clue:{ t:'Lying on your back, this is the muscle that lifts your head.', hers:1 },
    fact:'Sternum + clavicle → mastoid process. Named for its origins and insertion.' },
  { id:'zygomaticus', name:'Zygomaticus', her:1, region:'head', az:30,
    m:[/^zygomaticus (major|minor) muscle$/],
    clue:{ t:'The primary smiling muscle.', hers:1 },
    fact:'Pulls the corner of the mouth up. Facial muscles insert onto skin, not bone.' },
  { id:'serratus-anterior', name:'Serratus anterior', her:1, region:'trunk', az:30,
    m:['serratus anterior muscle'],
    clue:{ t:'Pulls the scapula forward — the antagonist of the trapezius.', hers:1 },
    fact:'Saw-toothed muscle on the side of the ribs. Moves the scapula forward; trapezius pulls it back.' },
  { id:'brachialis', name:'Brachialis', her:1, region:'upper', az:90,
    m:['brachialis muscle'],
    clue:{ t:'Pull-ups with the palms facing forward train this arm muscle.', hers:1 },
    fact:'Lies under the biceps brachii; a pure elbow flexor.' },

  // ── her labelled figure, back ──
  { id:'trapezius', name:'Trapezius', her:1, region:'upper', az:180,
    m:[/part of trapezius muscle$/],
    clue:{ t:'The kite-shaped muscle of the upper back.', hers:1 },
    fact:'Kite-shaped, upper back and neck. With latissimus dorsi, one of the two superficial back muscles.' },
  { id:'triceps', name:'Triceps brachii', her:1, region:'upper', az:165,
    m:[/head of triceps brachii$/],
    clue:{ t:'Straightens the arm at the elbow — the antagonist of the biceps, named for three origins.', hers:1 },
    fact:'Back of the upper arm. Extends the elbow. Three origins.' },
  { id:'latissimus', name:'Latissimus dorsi', her:1, region:'trunk', az:180,
    m:['latissimus dorsi muscle'],
    clue:{ t:'Swimmers have it particularly well developed — named for its dorsal position and breadth.', hers:1 },
    fact:'The broad muscle of the lower back ("lats").' },
  { id:'finger-extensors', name:'Finger extensors', sub:'back of forearm', her:1, region:'forearm', az:180,
    m:[/^extensor digitorum$/, 'extensor digiti minimi', 'extensor indicis', /^extensor carpi radialis (brevis|longus)$/, /extensor carpi ulnaris$/],
    fact:'The posterior forearm group — straightens the fingers and wrist.' },
  { id:'gluteus-maximus', name:'Gluteus maximus', her:1, region:'lower', az:180,
    m:['gluteus maximus muscle'],
    clue:{ t:'The largest buttock muscle — avoided for injections because the sciatic nerve runs under it.', hers:1 },
    fact:'Largest gluteal muscle. NOT the preferred IM site: the sciatic nerve lies beneath it.' },
  { id:'gluteus-medius', name:'Gluteus medius', her:1, region:'lower', az:130,
    m:['gluteus medius muscle'],
    clue:{ t:'The gluteal muscle that IS used for intramuscular injection; named for relative size.', hers:1 },
    fact:'Above and lateral to gluteus maximus. The safer gluteal injection site. Named for relative size.' },
  { id:'hamstrings', name:'Hamstrings', her:1, region:'lower', az:180,
    m:[/head of biceps femoris$/, 'semimembranosus muscle', 'semitendinosus muscle'],
    clue:{ t:'The muscle group that flexes the leg at the knee.', hers:1 },
    fact:'Biceps femoris + semitendinosus + semimembranosus, back of the thigh. Flex the knee.' },
  { id:'biceps-femoris', name:'Biceps femoris', her:1, region:'lower', az:165,
    m:[/head of biceps femoris$/],
    clue:{ t:'The hamstring muscle with two origins.', hers:1 },
    fact:'The lateral hamstring. Two heads, hence "biceps".' },
  { id:'gastrocnemius', name:'Gastrocnemius', her:1, region:'leg', az:180,
    m:[/head of gastrocnemius$/],
    clue:{ t:'Named for its belly shape; contract it to stand on your toes (a second-class lever).', hers:1 },
    fact:'The two-headed calf muscle. With the soleus it forms the triceps surae, inserting on the Achilles tendon.' },
  { id:'soleus', name:'Soleus', her:1, region:'leg', az:95,
    m:['soleus muscle'], fact:'Flat muscle under the gastrocnemius; shares the calcaneal (Achilles) tendon.' },
  { id:'achilles', name:'Calcaneal tendon', alt:'Achilles tendon', her:1, region:'leg', az:180,
    m:['calcaneal tendon'],
    clue:{ t:'Also known as the Achilles tendon.', hers:1 },
    fact:'Achilles tendon — joins gastrocnemius and soleus to the calcaneus. Tendons join muscle to bone.' },
  { id:'rectus-femoris', name:'Rectus femoris', her:1, region:'lower', az:5,
    m:['rectus femoris muscle'], fact:'The quadriceps head down the middle of the thigh. Vastus intermedius lies directly behind it.' },
  { id:'vastus-lateralis', name:'Vastus lateralis', her:1, region:'lower', az:60,
    m:['vastus lateralis muscle'],
    clue:{ t:'The large lateral thigh muscle — injection site for infants and for self-injection.', hers:1 },
    fact:'Lateral quadriceps head, named for size and location. IM site for infants.' },

  // ── her list, cannot be reached from outside ──
  { id:'vastus-intermedius', name:'Vastus intermedius', her:1, deep:1, region:'lower', az:10,
    m:['vastus intermedius muscle'],
    clue:{ t:'The thigh muscle found directly behind the rectus femoris.', hers:1 },
    fact:'The deep quadriceps head, hidden behind rectus femoris.' },
  { id:'erector-spinae', name:'Erector spinae', her:1, deep:1, region:'trunk', az:180,
    m:[/^(iliocostalis|longissimus|spinalis) /],
    clue:{ t:'The back muscles most susceptible to injury during heavy lifting.', hers:1 },
    fact:'Iliocostalis + longissimus + spinalis: the deep columns either side of the spine, under trapezius and latissimus dorsi.' },
  { id:'diaphragm', name:'Diaphragm', her:1, deep:1, region:'trunk', az:20, el:-10,
    m:['diaphragm'],
    clue:{ t:'The most important muscle for breathing in.', hers:1 },
    fact:'The dome under the lungs. Contracts and flattens to draw air in.' },
  { id:'rotator-cuff', name:'Rotator cuff', her:1, deep:1, region:'upper', az:180,
    m:['supraspinatus muscle', 'infraspinatus muscle', 'teres minor muscle', 'subscapularis muscle'],
    clue:{ t:'Supraspinatus, infraspinatus, teres minor and subscapularis together.', hers:1 },
    fact:'Four muscles wrapping the shoulder joint: supraspinatus, infraspinatus, teres minor, subscapularis.' },

  // ── beyond her list ──
  { id:'pec-minor', name:'Pectoralis minor', deep:1, region:'upper', az:0, m:['pectoralis minor muscle'], fact:'Under pectoralis major. Named for relative size.' },
  { id:'masseter', name:'Masseter', region:'head', az:60, m:[/part of masseter$/], fact:'The chewing muscle at the angle of the jaw.' },
  { id:'temporalis', name:'Temporalis', region:'head', az:80, m:['temporalis muscle'], fact:'Fan-shaped chewing muscle on the side of the skull.' },
  { id:'frontalis', name:'Frontalis', region:'head', az:10, m:['frontalis muscle'], fact:'Raises the eyebrows.' },
  { id:'orbicularis-oculi', name:'Orbicularis oculi', region:'head', az:20, m:[/part of orbicularis oculi$/], fact:'The ring around the eye — closes it. Named for its circular shape.' },
  { id:'orbicularis-oris', name:'Orbicularis oris', region:'head', az:10, m:['orbicularis oris muscle'], fact:'The ring around the mouth.' },
  { id:'teres-major', name:'Teres major', region:'upper', az:180, m:['teres major muscle'], fact:'Below the rotator cuff on the back of the scapula (teres MINOR is the cuff muscle).' },
  { id:'rhomboids', name:'Rhomboids', deep:1, region:'upper', az:180, m:[/^rhomboid (major|minor) muscle$/], fact:'Under the trapezius, from spine to scapula. Named for their shape.' },
  { id:'brachioradialis', name:'Brachioradialis', region:'forearm', az:20, m:['brachioradialis muscle'], fact:'The thumb-side forearm muscle that crosses the elbow.' },
  { id:'adductors', name:'Adductors', region:'lower', az:0, m:[/^adductor (brevis|longus|magnus)$/, 'gracilis muscle', 'pectineus muscle'], fact:'Inner-thigh group — pulls the thigh toward the midline. Named for their action.' },
  { id:'tfl', name:'Tensor fasciae latae', region:'lower', az:70, m:['tensor fasciae latae'], fact:'Small muscle at the lateral hip; it tightens the iliotibial tract (the band down the outer thigh, left out here so you can see vastus lateralis).' },
  { id:'fibularis-longus', name:'Fibularis longus', region:'leg', az:100, m:['fibularis longus muscle'], fact:'Runs down the lateral side of the lower leg, along the fibula.' },
  { id:'iliopsoas', name:'Iliopsoas', deep:1, region:'trunk', az:0, m:['iliacus muscle', 'psoas major'], fact:'Iliacus + psoas major — the deep hip flexor.' },
];

/* Meshes that never appear: they wrap, clutter or hide what is being asked. */
export const HIDE = {
  bone: [/^(incus|malleus|stapes)$/, /^sesamoid/, /cells of ethmoid/, /^sinus of/, /(arytenoid|corniculate|cricoid|thyroid) cartilage$/, /nasal septal cartilage$/, /alar cartilage$/],
  muscleMaterial: /^(Fascia|Bursa|Articular capsule)$/,
  muscle: [/^platysma$/, /^iliotibial tract$/, /^temporoparietalis/, /retinaculum/, /^iliopectineal arch$/, /aponeurosis$/, /(metacarpal|metatarsal) ligament$/, /fibrous sheath/],
};

/* The rectus sheath: in the model (as in life) the oblique aponeuroses run in front of rectus
 * abdominis to the midline, so the six-pack is invisible. Textbook figures cut the sheath away;
 * so do we — these meshes are clipped inside |x| < x metres, for the eye and for the tap. */
export const CLIP = [{ m:[/^(external|internal) abdominal oblique muscle$/], x:0.086 }];

/* Camera frames: a region is the union of the bones matched here. `side` keeps one limb. */
export const REGIONS = {
  whole:   { m:[/./], pad:1.05 },
  head:    { m:[/^(frontal|parietal|occipital|temporal|sphenoid|zygomatic|nasal) bone$/, 'maxilla', 'mandible', 'hyoid bone', /^vertebra c\d$/, /^(atlas|axis)/], pad:1.25 },
  upper:   { m:[/^(frontal|parietal|occipital) bone$/, 'mandible', / rib$/, /sternum$/, /^vertebra/, 'clavicle', 'scapula', 'humerus', 'radius', 'ulna', 'hip bone', /metacarpal/], pad:1.05 },
  trunk:   { m:[/ rib$/, /sternum$/, /^vertebra/, 'clavicle', 'scapula', 'hip bone', 'sacrum'], pad:1.1 },
  forearm: { m:['radius', 'ulna', /metacarpal/, /of hand$/], side:'L', pad:1.25 },
  hand:    { m:[/^(capitate|hamate|lunate|pisiform|scaphoid|trapezium|trapezoid|triquetrum) bone$/, /metacarpal/, /of hand$/], side:'L', pad:1.5 },
  pelvis:  { m:['hip bone', 'sacrum', 'coccyx', /^vertebra l[45]$/], pad:1.3 },
  lower:   { m:['hip bone', 'femur', 'patella', 'tibia', 'fibula', 'calcaneus', /metatarsal/], pad:1.05 },
  femur:   { m:['femur'], pad:1.15 },
  leg:     { m:['patella', 'tibia', 'fibula', 'calcaneus', 'talus', /metatarsal/], pad:1.15 },
  foot:    { m:[/^(calcaneus|talus|cuboid bone|navicular bone)$/, /cuneiform/, /metatarsal/, /of foot$/], pad:1.4 },
};

export const SETS = {
  bones: [
    { id:'her',       name:'Her list',      hint:'Every bone her Module 2 quizzes key', f:i => i.her && (!i.on || /^(ilium|ischium|pubis)$/.test(i.id)) },   // her 22-label figure asks ilium, ischium and pubis by name
    { id:'landmarks', name:'Femur & hip',   hint:'Ilium · ischium · pubis · trochanters · condyles', f:i => !!i.on },
    { id:'axial',     name:'Skull & spine', hint:'Cranial bones, vertebrae, sternum parts', f:i => !i.on && /^(cranium|mandible|maxilla|hyoid|frontal|parietal|temporal|occipital|zygomatic|nasal|cervical|thoracic|lumbar|sacrum|coccyx|atlas|axis|manubrium|xiphoid|true-ribs|false-ribs|floating-ribs)$/.test(i.id) },
    { id:'all',       name:'Everything',    hint:'All of it', f:() => true },
  ],
  muscles: [
    { id:'her',   name:'Her list',   hint:'Every muscle her Module 2 quizzes key', f:i => i.her },
    { id:'front', name:'Front',      hint:'Seen from the front', f:i => !i.deep && (i.az < 90 || i.az > 270) },
    { id:'back',  name:'Back',       hint:'Seen from behind', f:i => !i.deep && i.az >= 90 && i.az <= 270 },
    { id:'all',   name:'Everything', hint:'All of it', f:() => true },
  ],
};
